AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates a static website using S3 and CloudFront for deploying Merchant Center
  Custom Applications
Parameters:
  BucketName:
    Type: String
    Description: The name for the bucket hosting your website
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Website Configuration
        Parameters:
          - BucketName
    ParameterLabels:
      BucketName:
        default: S3 Bucket Name
  'AWS::CloudFormation::Designer':
    21536d00-1314-4a1e-a98a-26b8d7207fc6:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 210
      z: 1
      embeds: []
    0c1ae1d9-61ec-4b3a-9a50-0030e36a4850:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 210
      z: 1
      embeds: []
    40fa15a9-ab01-4186-b51f-5af5840b0a34:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 330
      z: 1
      embeds: []
      isassociatedwith:
        - 21536d00-1314-4a1e-a98a-26b8d7207fc6
    d41acf3f-7233-4d74-96d3-6dfcc7b818ca:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 330
      z: 1
      embeds: []
    274df6ab-f76f-4163-b4b8-34da988e3911:
      size:
        width: 60
        height: 60
      position:
        x: -60
        'y': 330
      z: 1
      embeds: []
    6acc5ead-32c3-4c73-8c87-f91dc45ef50b:
      size:
        width: 60
        height: 60
      position:
        x: -60
        'y': 210
      z: 1
      embeds: []
      isassociatedwith:
        - 274df6ab-f76f-4163-b4b8-34da988e3911
    f5f0e224-6eef-4c41-ba1a-f727f73effab:
      size:
        width: 60
        height: 60
      position:
        x: 50
        'y': 210
      z: 1
      embeds: []
      isassociatedwith:
        - 6acc5ead-32c3-4c73-8c87-f91dc45ef50b
Resources:
  AndinaIPSetWhitelist:
    Type: 'AWS::WAF::IPSet'
    Properties:
      Name: IPSet for whitelisted IP adresses
      IPSetDescriptors:
        - Type: IPV4
          Value: 190.100.210.0/24
        - Type: IPV4
          Value: 190.22.44.18.0/24
        - Type: IPV4
          Value: 186.105.14.0/24
        - Type: IPV4
          Value: 181.42.160.0/24
        - Type: IPV4
          Value: 181.42.161.0/24
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 274df6ab-f76f-4163-b4b8-34da988e3911
  AndinaIPSetRule:
    Type: 'AWS::WAF::Rule'
    Properties:
      Name: AndinaIPSetRule
      MetricName: AndinaIPSetRule
      Predicates:
        - DataId:
            Ref: AndinaIPSetWhitelist
          Negated: false
          Type: IPMatch
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6acc5ead-32c3-4c73-8c87-f91dc45ef50b
  CloudFrontACL:
    Type: 'AWS::WAF::WebACL'
    Properties:
      Name: WebACL to block Whitelisted IP addresses
      DefaultAction:
        Type: BLOCK
      MetricName: CloudFrontACL
      Rules:
        - Action:
            Type: ALLOW
          Priority: 1
          RuleId:
            Ref: AndinaIPSetRule
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f5f0e224-6eef-4c41-ba1a-f727f73effab
  WebsiteBucket:
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            Id: OpenCors
            MaxAge: '3600'
    Type: 'AWS::S3::Bucket'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 21536d00-1314-4a1e-a98a-26b8d7207fc6
  WebsiteBucketPolicy:
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: '1'
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebsiteBucket
                - /*
    Type: 'AWS::S3::BucketPolicy'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 40fa15a9-ab01-4186-b51f-5af5840b0a34
  CloudFrontOAI:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: access-identity-passport-front.s3.amazonaws.com
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d41acf3f-7233-4d74-96d3-6dfcc7b818ca
  WebsiteCloudFront:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn:
      - WebsiteBucket
    Properties:
      DistributionConfig:
        WebACLId:
          Ref: CloudFrontACL
        Origins:
          - DomainName: !GetAtt 
              - WebsiteBucket
              - RegionalDomainName
            Id: !Ref WebsiteBucket
            S3OriginConfig:
              OriginAccessIdentity: !Join 
                - ''
                - - origin-access-identity/cloudfront/
                  - !Ref CloudFrontOAI
        Enabled: 'true'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Ref WebsiteBucket
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: false
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
            Headers:
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
              - Origin
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0c1ae1d9-61ec-4b3a-9a50-0030e36a4850
Outputs:
  S3WebsiteURL:
    Value: !GetAtt 
      - WebsiteBucket
      - WebsiteURL
  CloudFrontDomain:
    Value: !GetAtt 
      - WebsiteCloudFront
      - DomainName
